openapi: 3.0.0
info:
  description: spirits is a turn-based battle royale game
  title: spirits
  version: 0.0.1
servers:
- description: The hosted spirits gameserver
  url: https://oh-great-spirits.herokuapp.com
paths:
  /:
    get:
      description: Retrieve the OpenAPI specification currently served
      responses:
        "200":
          content:
            application/json:
              schema:
                description: Object conforming to the OpenAPI standard
                type: object
          description: Successful response
  /sessions:
    get:
      description: List Sessions
      operationId: listSessions
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Session'
          description: Successful Sessions list
      security:
      - oidc:
        - spirits:sessions.write
        - spirits:sessions.read
      tags:
      - Sessions
    post:
      description: Create a Session
      operationId: createSessions
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Session'
        description: Session to create
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Session'
          description: Successful Session create
      security:
      - oidc:
        - spirits:sessions.write
      tags:
      - Sessions
  /sessions/{sessionName}:
    delete:
      description: Watch Session
      operationId: deleteSessions
      parameters:
      - description: Session name
        explode: false
        in: path
        name: sessionName
        required: true
        schema:
          description: Session name
          minLength: 1
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Session'
          description: Successful Session delete
      security:
      - oidc:
        - spirits:sessions.write
      tags:
      - Sessions
    get:
      description: Get Session
      operationId: getSessions
      parameters:
      - description: Session name
        explode: false
        in: path
        name: sessionName
        required: true
        schema:
          description: Session name
          minLength: 1
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Session'
          description: Successful Session get
      security:
      - oidc:
        - spirits:sessions.write
        - spirits:sessions.read
      tags:
      - Sessions
    put:
      description: Update Session
      operationId: updateSessions
      parameters:
      - description: Session name
        explode: false
        in: path
        name: sessionName
        required: true
        schema:
          description: Session name
          minLength: 1
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Session'
        description: Session to update
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Session'
          description: Successful Session update
      security:
      - oidc:
        - spirits:sessions.write
      tags:
      - Sessions
  /sessions/{sessionName}/teams:
    get:
      description: List Teams
      operationId: listSessionTeams
      parameters:
      - description: Team name
        explode: false
        in: path
        name: sessionName
        required: true
        schema:
          description: Team name
          minLength: 1
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Team'
          description: Successful Teams list
      security:
      - oidc:
        - spirits:sessions:teams.write
        - spirits:sessions:teams.read
      tags:
      - SessionTeams
    post:
      description: Create a Team
      operationId: createSessionTeams
      parameters:
      - description: Team name
        explode: false
        in: path
        name: sessionName
        required: true
        schema:
          description: Team name
          minLength: 1
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Team'
        description: Team to create
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Team'
          description: Successful Team create
      security:
      - oidc:
        - spirits:sessions:teams.write
      tags:
      - SessionTeams
  /sessions/{sessionName}/teams/{teamName}:
    delete:
      description: Watch Team
      operationId: deleteSessionTeams
      parameters:
      - description: Team name
        explode: false
        in: path
        name: sessionName
        required: true
        schema:
          description: Team name
          minLength: 1
          type: string
        style: simple
      - description: Team name
        explode: false
        in: path
        name: teamName
        required: true
        schema:
          description: Team name
          minLength: 1
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Team'
          description: Successful Team delete
      security:
      - oidc:
        - spirits:sessions:teams.write
      tags:
      - SessionTeams
    get:
      description: Get Team
      operationId: getSessionTeams
      parameters:
      - description: Team name
        explode: false
        in: path
        name: sessionName
        required: true
        schema:
          description: Team name
          minLength: 1
          type: string
        style: simple
      - description: Team name
        explode: false
        in: path
        name: teamName
        required: true
        schema:
          description: Team name
          minLength: 1
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Team'
          description: Successful Team get
      security:
      - oidc:
        - spirits:sessions:teams.write
        - spirits:sessions:teams.read
      tags:
      - SessionTeams
    put:
      description: Update Team
      operationId: updateSessionTeams
      parameters:
      - description: Team name
        explode: false
        in: path
        name: sessionName
        required: true
        schema:
          description: Team name
          minLength: 1
          type: string
        style: simple
      - description: Team name
        explode: false
        in: path
        name: teamName
        required: true
        schema:
          description: Team name
          minLength: 1
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Team'
        description: Team to update
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Team'
          description: Successful Team update
      security:
      - oidc:
        - spirits:sessions:teams.write
      tags:
      - SessionTeams
  /sessions/{sessionName}/teams/{teamName}/spirits:
    get:
      description: List Spirits
      operationId: listSessionTeamSpirits
      parameters:
      - description: Spirit name
        explode: false
        in: path
        name: sessionName
        required: true
        schema:
          description: Spirit name
          minLength: 1
          type: string
        style: simple
      - description: Spirit name
        explode: false
        in: path
        name: teamName
        required: true
        schema:
          description: Spirit name
          minLength: 1
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Spirit'
          description: Successful Spirits list
      security:
      - oidc:
        - spirits:sessions:teams:spirits.write
        - spirits:sessions:teams:spirits.read
      tags:
      - SessionTeamSpirits
    post:
      description: Create a Spirit
      operationId: createSessionTeamSpirits
      parameters:
      - description: Spirit name
        explode: false
        in: path
        name: sessionName
        required: true
        schema:
          description: Spirit name
          minLength: 1
          type: string
        style: simple
      - description: Spirit name
        explode: false
        in: path
        name: teamName
        required: true
        schema:
          description: Spirit name
          minLength: 1
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Spirit'
        description: Spirit to create
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Spirit'
          description: Successful Spirit create
      security:
      - oidc:
        - spirits:sessions:teams:spirits.write
      tags:
      - SessionTeamSpirits
  /sessions/{sessionName}/teams/{teamName}/spirits/{spiritName}:
    delete:
      description: Watch Spirit
      operationId: deleteSessionTeamSpirits
      parameters:
      - description: Spirit name
        explode: false
        in: path
        name: sessionName
        required: true
        schema:
          description: Spirit name
          minLength: 1
          type: string
        style: simple
      - description: Spirit name
        explode: false
        in: path
        name: teamName
        required: true
        schema:
          description: Spirit name
          minLength: 1
          type: string
        style: simple
      - description: Spirit name
        explode: false
        in: path
        name: spiritName
        required: true
        schema:
          description: Spirit name
          minLength: 1
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Spirit'
          description: Successful Spirit delete
      security:
      - oidc:
        - spirits:sessions:teams:spirits.write
      tags:
      - SessionTeamSpirits
    get:
      description: Get Spirit
      operationId: getSessionTeamSpirits
      parameters:
      - description: Spirit name
        explode: false
        in: path
        name: sessionName
        required: true
        schema:
          description: Spirit name
          minLength: 1
          type: string
        style: simple
      - description: Spirit name
        explode: false
        in: path
        name: teamName
        required: true
        schema:
          description: Spirit name
          minLength: 1
          type: string
        style: simple
      - description: Spirit name
        explode: false
        in: path
        name: spiritName
        required: true
        schema:
          description: Spirit name
          minLength: 1
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Spirit'
          description: Successful Spirit get
      security:
      - oidc:
        - spirits:sessions:teams:spirits.write
        - spirits:sessions:teams:spirits.read
      tags:
      - SessionTeamSpirits
    put:
      description: Update Spirit
      operationId: updateSessionTeamSpirits
      parameters:
      - description: Spirit name
        explode: false
        in: path
        name: sessionName
        required: true
        schema:
          description: Spirit name
          minLength: 1
          type: string
        style: simple
      - description: Spirit name
        explode: false
        in: path
        name: teamName
        required: true
        schema:
          description: Spirit name
          minLength: 1
          type: string
        style: simple
      - description: Spirit name
        explode: false
        in: path
        name: spiritName
        required: true
        schema:
          description: Spirit name
          minLength: 1
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Spirit'
        description: Spirit to update
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Spirit'
          description: Successful Spirit update
      security:
      - oidc:
        - spirits:sessions:teams:spirits.write
      tags:
      - SessionTeamSpirits
  /sessions/{sessionName}/battles:
    get:
      description: List Battles
      operationId: listSessionBattles
      parameters:
      - description: Battle name
        explode: false
        in: path
        name: sessionName
        required: true
        schema:
          description: Battle name
          minLength: 1
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Battle'
          description: Successful Battles list
      security:
      - oidc:
        - spirits:sessions:battles.write
        - spirits:sessions:battles.read
      tags:
      - SessionBattles
    post:
      description: Create a Battle
      operationId: createSessionBattles
      parameters:
      - description: Battle name
        explode: false
        in: path
        name: sessionName
        required: true
        schema:
          description: Battle name
          minLength: 1
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Battle'
        description: Battle to create
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Battle'
          description: Successful Battle create
      security:
      - oidc:
        - spirits:sessions:battles.write
      tags:
      - SessionBattles
  /sessions/{sessionName}/battles/{battleName}:
    delete:
      description: Watch Battle
      operationId: deleteSessionBattles
      parameters:
      - description: Battle name
        explode: false
        in: path
        name: sessionName
        required: true
        schema:
          description: Battle name
          minLength: 1
          type: string
        style: simple
      - description: Battle name
        explode: false
        in: path
        name: battleName
        required: true
        schema:
          description: Battle name
          minLength: 1
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Battle'
          description: Successful Battle delete
      security:
      - oidc:
        - spirits:sessions:battles.write
      tags:
      - SessionBattles
    get:
      description: Get Battle
      operationId: getSessionBattles
      parameters:
      - description: Battle name
        explode: false
        in: path
        name: sessionName
        required: true
        schema:
          description: Battle name
          minLength: 1
          type: string
        style: simple
      - description: Battle name
        explode: false
        in: path
        name: battleName
        required: true
        schema:
          description: Battle name
          minLength: 1
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Battle'
          description: Successful Battle get
      security:
      - oidc:
        - spirits:sessions:battles.write
        - spirits:sessions:battles.read
      tags:
      - SessionBattles
  /sessions/{sessionName}/battles/{battleName}/spirits:
    get:
      description: List Spirits
      operationId: listSessionBattleSpirits
      parameters:
      - description: Spirit name
        explode: false
        in: path
        name: sessionName
        required: true
        schema:
          description: Spirit name
          minLength: 1
          type: string
        style: simple
      - description: Spirit name
        explode: false
        in: path
        name: battleName
        required: true
        schema:
          description: Spirit name
          minLength: 1
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Spirit'
          description: Successful Spirits list
      security:
      - oidc:
        - spirits:sessions:battles:spirits.write
        - spirits:sessions:battles:spirits.read
      tags:
      - SessionBattleSpirits
  /sessions/{sessionName}/battles/{battleName}/spirits/{spiritName}:
    get:
      description: Get Spirit
      operationId: getSessionBattleSpirits
      parameters:
      - description: Spirit name
        explode: false
        in: path
        name: sessionName
        required: true
        schema:
          description: Spirit name
          minLength: 1
          type: string
        style: simple
      - description: Spirit name
        explode: false
        in: path
        name: battleName
        required: true
        schema:
          description: Spirit name
          minLength: 1
          type: string
        style: simple
      - description: Spirit name
        explode: false
        in: path
        name: spiritName
        required: true
        schema:
          description: Spirit name
          minLength: 1
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Spirit'
          description: Successful Spirit get
      security:
      - oidc:
        - spirits:sessions:battles:spirits.write
        - spirits:sessions:battles:spirits.read
      tags:
      - SessionBattleSpirits
  /sessions/{sessionName}/battles/{battleName}/spirits/{spiritName}/actions:
    post:
      description: Create a Action
      operationId: createSessionBattleSpiritActions
      parameters:
      - description: Action name
        explode: false
        in: path
        name: sessionName
        required: true
        schema:
          description: Action name
          minLength: 1
          type: string
        style: simple
      - description: Action name
        explode: false
        in: path
        name: battleName
        required: true
        schema:
          description: Action name
          minLength: 1
          type: string
        style: simple
      - description: Action name
        explode: false
        in: path
        name: spiritName
        required: true
        schema:
          description: Action name
          minLength: 1
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Action'
        description: Action to create
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Action'
          description: Successful Action create
      security:
      - oidc:
        - spirits:sessions:battles:spirits:actions.write
      tags:
      - SessionBattleSpiritActions
components:
  schemas:
    Action:
      description: A reference to a Spirit's Action
      example:
        name: name
      properties:
        name:
          description: The name of a Spirit's Action
          minLength: 1
          type: string
      required:
      - name
      type: object
    Battle:
      description: A skirmish amongst Spirit's
      example:
        name: name
        spirits:
        - spirits
        - spirits
      properties:
        name:
          description: The unique name of this Battle
          minLength: 1
          type: string
        spirits:
          description: The spirits involved in this Battle.
          items:
            description: A name of a Spirit object involved in this Battle
            type: string
          maxLength: 2
          minLength: 2
          type: array
      required:
      - name
      - spirits
      type: object
    Session:
      description: An isolated collection of Battle's and Team's
      example:
        auth:
          oidc:
            issuer: issuer
        name: name
      properties:
        name:
          description: The unique name of this Session
          minLength: 1
          type: string
        auth:
          $ref: '#/components/schemas/Session_auth'
      required:
      - name
      type: object
    Spirit:
      description: An actor in a Battle
      example:
        stats:
          armor: 0
          health: 1
          power: 0
          agility: 0
        name: name
        actions:
        - actions
        - actions
        intelligence: roundRobin
      properties:
        name:
          description: The unique name of this Spirit
          minLength: 1
          type: string
        stats:
          $ref: '#/components/schemas/Spirit_stats'
        actions:
          default:
          - attack
          description: The Action's that this Spirit can perform
          items:
            description: The name of an Action
            type: string
          type: array
        intelligence:
          default: roundRobin
          description: The AI setting for this Spirit
          type: string
      required:
      - name
      - stats
      type: object
    Team:
      description: A collection Spirit's
      example:
        name: name
      properties:
        name:
          description: The unique name of this Team
          minLength: 1
          type: string
      required:
      - name
      type: object
    Session_auth_oidc:
      description: OIDC authentication configuration
      example:
        issuer: issuer
      properties:
        issuer:
          description: OIDC issuer to use for authentication
          minLength: 1
          pattern: ^https://.*
          type: string
      type: object
    Session_auth:
      description: A description of the auth requirements for this Session; defaults
        to using the well-known OIDC provider
      example:
        oidc:
          issuer: issuer
      properties:
        oidc:
          $ref: '#/components/schemas/Session_auth_oidc'
      type: object
    Spirit_stats:
      description: Quantitative properties of the Spirit; these are utilized and manipulated
        throughout the course of a Battle
      example:
        armor: 0
        health: 1
        power: 0
        agility: 0
      properties:
        health:
          description: "A quantitative representation of the energy of the Spirit;\
            \ when this drops to 0, the Spirit is no longer to participate in a Battle"
          format: int64
          minimum: 1
          type: integer
        power:
          default: 0
          description: A quantitative representation of the might of the Spirit
          format: int64
          minimum: 0
          type: integer
        armor:
          default: 0
          description: A quantitative representation of the defense of the Spirit
          format: int64
          minimum: 0
          type: integer
        agility:
          default: 0
          description: A quantitative representation of the speed of the Spirit
          format: int64
          minimum: 0
          type: integer
      required:
      - health
      type: object
  securitySchemes:
    oidc:
      openIdConnectUrl: https://oh-great-spirits.herokuapp.com
      type: openIdConnect
